[package]
name = "dice-roll"
version = "0.1.0"
authors = ["Jonathan Jones <gitmaster@thespooky.house>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rand = "0.7.3"
